language:
  - "node_js"

node_js:
  - "5.2"

before_install:
  - npm install

script:
  - "wget https://raw.githubusercontent.com/jonkemp/qunit-phantomjs-runner/master/runner.js"
  - "gulp prepare-tests"
  - "phantomjs runner.js test/index.html"