language:
  - "node_js"

node_js:
  - "7.5"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_install:
  - yarn global add typings

addons:
  sauce_connect: true

script:
  - "typings install"
  - "npm run test:ci"